# docker buildx build -t ghcr.io/qicongsheng/cloudflared --platform linux/amd64,linux/arm64 . --push
# =================================
# docker run -d --restart=always ghcr.io/qicongsheng/cloudflared tunnel --no-autoupdate run --token eyJhIjoiZTAwMWM4MzlmMTNiNzU2ZDc0YWI1NjE0MzFlM2ZlZDciLCJ0IjoiMTNjYmI4OTYtNjdkZS00NmY1LTkxOGEtZGE0YjA3NDNjMGE3IiwicyI6IlpUUTJaVGhpWXpjdE9HTXhZeTAwTm1OaUxXSmtZbU10TVRnd1lUZzVOelk0WldKaiJ9
# =================================
FROM cloudflare/cloudflared:latest
MAINTAINER qicongsheng

