# docker build -t ghcr.io/qicongsheng/shellngn . --push
# =================================
# docker run -d --restart=always -e HOST=0.0.0.0 -e PORT=8066 --net=host ghcr.io/qicongsheng/shellngn
# =================================
FROM shellngn/pro:4.1.1
MAINTAINER qicongsheng

ADD bundle.js /home/node/server

