FROM kalilinux/kali:latest
MAINTAINER qics
RUN apt-get update && apt-get upgrade
RUN apt-get install vim net-tools pciutils aircrack-ng openssh-server kmod iputils-ping telnet nmap hashcat -y

RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config 
RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config

ENV USER=root \
	PASSWD=123456

RUN echo '#!/bin/bash' >> /opt/startup.sh
RUN echo 'echo "user: $USER" ' >> /opt/startup.sh
RUN echo 'echo "passwd: $PASSWD" ' >> /opt/startup.sh
RUN echo 'useradd $USER' >> /opt/startup.sh
RUN echo 'echo $USER:$PASSWD | chpasswd' >> /opt/startup.sh
RUN echo '/etc/init.d/ssh restart' >> /opt/startup.sh
RUN echo 'tail -f /dev/null' >> /opt/startup.sh

RUN chmod +x /opt/startup.sh
RUN rm -fr /tmp/*
EXPOSE 22
CMD ["/opt/startup.sh"]
