# docker buildx build -t ghcr.io/qicongsheng/vaultwarden --platform linux/amd64,linux/arm64 . --push
# =================================
# mkdir -p /data/vaultwarden
# docker run -d --restart=always --name vaultwarden -v /data/vaultwarden/:/data/ -p 6068:80 ghcr.io/qicongsheng/vaultwarden
# =================================
FROM vaultwarden/server:latest
MAINTAINER qicongsheng
