# docker build -t ghcr.io/qicongsheng/tinyproxy .
# =================================
# docker run -d --restart=always -p 6666:8888 ghcr.io/qicongsheng/tinyproxy
# =================================
FROM monokal/tinyproxy:latest
MAINTAINER qicongsheng
