FROM python:3.9.17-alpine3.17
MAINTAINER qics

ENV WEB_PORT=1990 

RUN apk add gcc musl-dev libffi-dev \
    && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple webssh \
    && echo "#!/bin/sh" >> /opt/startup.sh \
    && echo "nohup wssh --fbidhttp=False --address='0.0.0.0' --port=$WEB_PORT &" >> /opt/startup.sh \
    && echo "tail -f /dev/null" >> /opt/startup.sh \
    && chmod +x /opt/startup.sh \
    && rm -fr /tmp/*
	
CMD ["/opt/startup.sh"]
