# docker buildx build -t ghcr.io/qicongsheng/traffmonetizer --platform linux/amd64,linux/arm64/v8 . --push
# =================================
# docker run -d --restart=always ghcr.io/qicongsheng/traffmonetizer start accept --token 5xijhElDM8IqEwMj0VolDEVsbUDCGS3GFpRCFckxix8=
# =================================
FROM traffmonetizer/cli_v2
MAINTAINER qicongsheng

