# docker buildx build -t ghcr.io/qicongsheng/ftp:server --platform linux/amd64,linux/arm64/v8 . --push
# =================================
# docker run -d --restart=always -e USERS="qics|Best12167|/tmp" -p 9021:21 --privileged=true -v /tmp:/tmp ghcr.io/qicongsheng/ftp:server
# =================================
FROM delfer/alpine-ftp-server
MAINTAINER qicongsheng
