# docker buildx build -t ghcr.io/qicongsheng/nascab --platform linux/amd64,linux/arm64/v8 . --push
# =================================
# docker run -d --restart=always -p 8888:80 -p 5555:90 ghcr.io/qicongsheng/nascab
# =================================
FROM ypptec/nascab
MAINTAINER qicongsheng

