# docker buildx build -t qics/debian --platform linux/amd64,linux/arm64/v8 . --push
FROM debian:latest
MAINTAINER qics

ENV USER=root \
    PASSWD=123456 \
    SSHD_PORT=22 \
    TZ=Asia/Shanghai 

RUN apt update --allow-releaseinfo-change && apt update && apt upgrade -y \
    && apt install -y sudo openssh-client openssh-server curl \
    && mkdir /var/run/sshd/ \
    && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config \
    && echo "alias ls='ls \$LS_OPTIONS --color'" >> /root/.bashrc \
    && echo "alias ll='ls \$LS_OPTIONS -l --color'" >> /root/.bashrc \

    && mv /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak \
    && curl -o /etc/apt/sources.list.d/ustc-debian12.sources https://www.qics.top/shell/debian/sources/ustc-debian12.sources \

    && echo '#!/bin/bash' >> /opt/startup.sh \
    && echo 'echo "Port $SSHD_PORT" >> /etc/ssh/sshd_config' >> /opt/startup.sh \
    && echo 'useradd $USER' >> /opt/startup.sh \
    && echo 'echo $USER:$PASSWD | chpasswd' >> /opt/startup.sh \
    && echo '/usr/sbin/sshd -D &' >> /opt/startup.sh \
    && echo 'echo plugin' >> /opt/startup.sh \
    && echo 'tail -f /dev/null' >> /opt/startup.sh \

    && chmod +x /opt/startup.sh \
    && apt autoclean \
    && rm -fr /tmp/*

CMD ["/opt/startup.sh"]
