FROM debian:11
MAINTAINER qics

ENV USER=root \
    PASSWD=123456\
    TZ=Asia/Shanghai 

RUN apt-get update \
    && apt-get install -y openssh-client openssh-server curl \
    && mkdir  /var/run/sshd/ && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config \
    && echo "alias ls='ls \$LS_OPTIONS --color'" >> /root/.bashrc \
    && echo "alias ll='ls \$LS_OPTIONS -l --color'" >> /root/.bashrc \
    
    && mv /etc/apt/sources.list /etc/apt/sources.list.bak \
    && curl -o /etc/apt/sources.list https://www.qics.top/shell/debian/sources/ali-debian11.list \
    
    && echo '#!/bin/bash' >> /opt/startup.sh \
    && echo 'echo "user: $USER" ' >> /opt/startup.sh \
    && echo 'echo "passwd: $PASSWD" ' >> /opt/startup.sh \
    && echo 'useradd $USER' >> /opt/startup.sh \
    && echo 'echo $USER:$PASSWD | chpasswd' >> /opt/startup.sh \
    && echo '/usr/sbin/sshd -D &' >> /opt/startup.sh \
    && echo 'tail -f /dev/null' >> /opt/startup.sh \
    
    && chmod +x /opt/startup.sh \
    && rm -fr /tmp/*

EXPOSE 22
CMD ["/opt/startup.sh"]
