FROM consol/debian-xfce-vnc
MAINTAINER qics

USER root

ENV USER=root \
    PASSWD=123456 
	
RUN apt update \
    && apt install -y openssh-client openssh-server \
    && mkdir  /var/run/sshd/ \
    && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config \
    && sed -i "s/VNC_PW/PASSWD/" /dockerstartup/vnc_startup.sh \
    && echo '#!/bin/bash' >> /opt/startup.sh \
    && echo 'echo "user: $USER" ' >> /opt/startup.sh \
    && echo 'echo "passwd: $PASSWD" ' >> /opt/startup.sh \
    && echo 'useradd $USER' >> /opt/startup.sh \
    && echo 'echo $USER:$PASSWD | chpasswd' >> /opt/startup.sh \
    && echo '/usr/sbin/sshd -D &' >> /opt/startup.sh \
    && echo 'tail -f /dev/null' >> /opt/startup.sh \

    && chmod +x /opt/startup.sh  \
    && rm -fr /tmp/*

EXPOSE 22
CMD ["/opt/startup.sh"]
