FROM alpine:3.15
MAINTAINER qics

RUN apk add n2n \
    && echo '#!/bin/sh' >> /opt/startup.sh \
    && echo 'supernode -p 6893' >> /opt/startup.sh \
    && echo 'tail -f /dev/null' >> /opt/startup.sh \

    && chmod +x /opt/startup.sh \
    && rm -fr /tmp/* \

EXPOSE 6893
CMD ["/opt/startup.sh"]

