# docker build -t qics/n2n:server .
FROM alpine:3.15 as builder
MAINTAINER qics

RUN apk add curl gcc make cmake alpine-sdk linux-headers openssl-dev \
    && curl -o /tmp/n2n.tar.gz https://cxajuq.sn.files.1drv.com/y4m1VhwoOoKfrNDnvzZHnrfIDr83HIVQti01przSH3YQBtbJan-QeOwtzvSpZ44pySbQBystMKZOq-Cr8W6MCyIPwNQ66XkSDe4DpcQAjc-qSI4P7D7fkFHU5IuJ00LXbEWbeCMk5-KekeMB3URlzQy8YxRn8XmZ8D8OD4FiPMo_zHQxFOH-VGA5MtRyso3X3O9qU5lvBPccMfLoX83pZ_Q9w \
    && tar -zxvf /tmp/n2n.tar.gz -C /tmp \
    && cd /tmp/n2n/n2n_v2 && make && make install

FROM alpine:3.15
RUN mkdir -p /usr/sbin /usr/share/man/man1 /usr/share/man/man7 /usr/share/man/man8 \
    && echo '#!/bin/sh' >> /opt/startup.sh \
    && echo 'supernode -l 6893' >> /opt/startup.sh \
    && echo 'tail -f /dev/null' >> /opt/startup.sh \
    && chmod +x /opt/startup.sh \
    && rm -fr /tmp/*

COPY --from=builder /tmp/n2n/n2n_v2/supernode /usr/sbin/
COPY --from=builder /tmp/n2n/n2n_v2/edge /usr/sbin/
COPY --from=builder /tmp/n2n/n2n_v2/edge.8.gz /usr/share/man/man8/
COPY --from=builder /tmp/n2n/n2n_v2/supernode.1.gz /usr/share/man/man1/
COPY --from=builder /tmp/n2n/n2n_v2/n2n_v2.7.gz /usr/share/man/man7/

EXPOSE 6893
CMD ["/opt/startup.sh"]

