FROM alpine:3.15
MAINTAINER qics

ENV DEVICE_NAME= \
    NET_GROUP= \
    PASSWD= \
    EDGE_IP= \
    SERVER_IP= \
    SERVER_PORT=

RUN apk add n2n \
    && mkdir -p /etc/n2n \
    && echo '#!/bin/sh' >> /opt/startup.sh \
    && echo 'rm -fr /etc/n2n/edge.cfg' >> /opt/startup.sh \
    && echo 'echo "-d=$DEVICE_NAME " >> /etc/n2n/edge.cfg ' >> /opt/startup.sh \
    && echo 'echo "-a=$IP " >> /etc/n2n/edge.cfg ' >> /opt/startup.sh \
    && echo 'echo "-c=$NET_GROUP " >> /etc/n2n/edge.cfg ' >> /opt/startup.sh \
    && echo 'echo "-k=$PASSWD " >> /etc/n2n/edge.cfg ' >> /opt/startup.sh \
    && echo 'echo "-l=$SERVER_IP:$SERVER_PORT " >> /etc/n2n/edge.cfg ' >> /opt/startup.sh \
    && echo 'edge /etc/n2n/edge.cfg' >> /opt/startup.sh \
    && echo 'tail -f /dev/null' >> /opt/startup.sh \

    && chmod +x /opt/startup.sh \
    && rm -fr /tmp/* \

EXPOSE 6893
CMD ["/opt/startup.sh"]

