FROM alpine:3.15
MAINTAINER qics

ENV DEVICE_NAME=0.52.3 \
    NET_GROUP= \
    PASSWD= \
    EDGE_IP= \
    SERVER_IP= \
    SERVER_PORT= \

RUN apk add n2n \
    && echo '#!/bin/sh' >> /opt/startup.sh \
    && echo 'edge -d ${DEVICE_NAME} -a ${IP} -c ${NET_GROUP} -k ${PASSWD} -l ${SERVER_IP}:${SERVER_PORT}' >> /opt/startup.sh \
    && echo 'tail -f /dev/null' >> /opt/startup.sh \

    && chmod +x /opt/startup.sh \
    && rm -fr /tmp/* \

EXPOSE 6893
CMD ["/opt/startup.sh"]

