# docker buildx build -t ghcr.io/qicongsheng/drawio --platform linux/amd64,linux/arm64/v8 . --push
# =================================
# docker run -d --restart=always -p 8080:8080 -p 8443:8443 ghcr.io/qicongsheng/drawio
# http://192.168.99.100:8080/
# https://192.168.99.100:8443/
# =================================
FROM jgraph/drawio
MAINTAINER qicongsheng

