# docker buildx build -t ghcr.io/qicongsheng/qinglong --platform linux/amd64,linux/arm64/v8 . --push
# =================================
# docker run -d --restart=always -p 5700:5700 -v /data/qinglong:/ql/data ghcr.io/qicongsheng/qinglong
# =================================
FROM whyour/qinglong:latest
MAINTAINER qicongsheng

