# docker buildx build -t ghcr.io/qicongsheng/netbird --platform linux/amd64,linux/arm64/v8 . --push
# =================================
# docker run -d --restart=always -e NB_SETUP_KEY=951ABD0D-6D3D-47BB-AD78-A8F5D26F5DA7 --net=host --privileged=true ghcr.io/qicongsheng/netbird
# =================================
FROM netbirdio/netbird:latest
MAINTAINER qicongsheng

