# docker build -t ghcr.io/qicongsheng/registry . --push
# =================================
# docker run -d --restart=always -p 5000:5000 -v /data/registry:/var/lib/registry ghcr.io/qicongsheng/registry
# =================================
FROM registry:2.8.3
MAINTAINER qicongsheng


