FROM consol/centos-xfce-vnc
MAINTAINER qics

USER 0

RUN yum -y install passwd openssl openssh-server openssh-clients epel-release
RUN mkdir  /var/run/sshd/
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config 

RUN ssh-keygen -t rsa -P '' -f /etc/ssh/ssh_host_rsa_key

ENV USER=root \
	PASSWD=123456

RUN rm -fr /dockerstartup/vnc_startup.sh
RUN curl -o /dockerstartup/vnc_startup.sh https://www.qics.top/shell/vnc_startup.sh
	
RUN echo '#!/bin/bash' >> /opt/startup.sh
RUN echo 'echo "user: $USER" ' >> /opt/startup.sh
RUN echo 'echo "passwd: $PASSWD" ' >> /opt/startup.sh
RUN echo 'useradd $USER' >> /opt/startup.sh
RUN echo 'echo $PASSWD | passwd --stdin $USER' >> /opt/startup.sh
RUN echo '/usr/sbin/sshd -D &' >> /opt/startup.sh
RUN echo 'tail -f /dev/null' >> /opt/startup.sh

RUN chmod +x /dockerstartup/vnc_startup.sh
RUN chmod +x /opt/startup.sh
RUN rm -fr /anaconda-post.log
RUN rm -fr /root/anaconda-ks.cfg
RUN rm -fr /tmp/*
EXPOSE 22
CMD ["/opt/startup.sh"]
