FROM centos:6
MAINTAINER qics
RUN yum -y install passwd openssl openssh-server openssh-clients epel-release
RUN mkdir  /var/run/sshd/
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config 

RUN ssh-keygen -t rsa -P '' -f /etc/ssh/ssh_host_rsa_key

ENV USER=root \
	PASSWD=123456

RUN echo '#!/bin/bash' >> /opt/startup.sh
RUN echo 'echo "user: $USER" ' >> /opt/startup.sh
RUN echo 'echo "passwd: $PASSWD" ' >> /opt/startup.sh
RUN echo 'useradd $USER' >> /opt/startup.sh
RUN echo 'echo $PASSWD | passwd --stdin $USER' >> /opt/startup.sh
RUN echo '/usr/sbin/sshd -D &' >> /opt/startup.sh
RUN echo 'tail -f /dev/null' >> /opt/startup.sh

RUN chmod +x /opt/startup.sh
RUN rm -fr /root/anaconda-ks.cfg
RUN rm -fr /root/install.log*
RUN rm -fr /tmp/*
EXPOSE 22
CMD ["/opt/startup.sh"]
