FROM centos:7
MAINTAINER qics
RUN yum -y install passwd openssl openssh-server openssh-clients epel-release sysvinit-tools cronie
RUN curl -o /usr/local/bin/blockip.sh http://www.qics.top/shell/blockip.sh
RUN mkdir  /var/run/sshd/
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config 

RUN ssh-keygen -t rsa -P '' -f /etc/ssh/ssh_host_rsa_key

ENV USER=root \
	PASSWD=123456

RUN echo '#!/bin/bash' >> /opt/startup.sh
RUN echo 'echo "user: $USER" ' >> /opt/startup.sh
RUN echo 'echo "passwd: $PASSWD" ' >> /opt/startup.sh
RUN echo 'useradd $USER' >> /opt/startup.sh
RUN echo 'echo $PASSWD | passwd --stdin $USER' >> /opt/startup.sh
RUN echo '/usr/sbin/sshd -D &' >> /opt/startup.sh
RUN echo 'nohup crond -n > /dev/null 2>&1 &' >> /opt/startup.sh
RUN echo 'echo "*/1 * * * * /usr/local/bin/blockip.sh" >> /var/spool/cron/root' >> /opt/startup.sh
RUN echo 'tail -f /dev/null' >> /opt/startup.sh

RUN chmod +x /opt/startup.sh
RUN chmod +x /usr/local/bin/blockip.sh
RUN rm -fr /anaconda-post.log
RUN rm -fr /root/anaconda-ks.cfg
RUN rm -fr /tmp/*
EXPOSE 22
CMD ["/opt/startup.sh"]



