# docker build -t ghcr.io/qicongsheng/chrome .
# Start a Standalone Chrome
# docker run -d -p 4444:4444 -p 7900:7900 ghcr.io/qicongsheng/chrome
# Point your WebDriver tests
# http://localhost:4444
# To see what is happening inside the container
# http://localhost:7900/?autoconnect=1&resize=scale&password=secret
FROM selenium/standalone-chrome:latest
MAINTAINER qicongsheng

