FROM ubuntu:20.04
MAINTAINER qics
RUN apt-get update 
RUN apt-get install -y openssh-client openssh-server
RUN mkdir  /var/run/sshd/
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config 

ENV USER=root \
	PASSWD=123456

RUN echo '#!/bin/bash' >> /opt/startup.sh
RUN echo 'echo "user: $USER" ' >> /opt/startup.sh
RUN echo 'echo "passwd: $PASSWD" ' >> /opt/startup.sh
RUN echo 'useradd $USER' >> /opt/startup.sh
RUN echo 'echo $USER:$PASSWD | chpasswd' >> /opt/startup.sh
RUN echo '/usr/sbin/sshd -D &' >> /opt/startup.sh
RUN echo 'tail -f /dev/null' >> /opt/startup.sh

RUN chmod +x /opt/startup.sh
RUN rm -fr /tmp/*
EXPOSE 22
CMD ["/opt/startup.sh"]