# docker buildx build -t ghcr.io/qicongsheng/jellyfin --platform linux/amd64,linux/arm64/v8 . --push
# docker run -d --restart=always -v /tmp:/tmp --privileged=true -p 8096:8096 ghcr.io/qicongsheng/jellyfin
FROM jellyfin/jellyfin
MAINTAINER qicongsheng

RUN mkdir /data && chmod -R 777 /data



