# docker build -t ghcr.io/qicongsheng/cloudreve . --push
FROM xavierniu/cloudreve:3.2.1
MAINTAINER qics

RUN apk add python2 && apk add yasm && apk add ffmpeg \
    && wget -P /tmp https://bootstrap.pypa.io/pip/2.7/get-pip.py \
    && python /tmp/get-pip.py \
    && pip install pysqlite3 \
    && wget -P /cloudreve https://www.qics.top/software/cloudreve/convert2mp4.py \
    && rm -fr /cloudreve/entrypoint.sh \
    && wget -P /cloudreve https://www.qics.top/software/cloudreve/entrypoint.sh \
    && chmod +x /cloudreve/entrypoint.sh \
    && rm -fr /tmp/*

EXPOSE 5212
